apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # namespace: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: multi-app-project-python-app:latest # This will be overridden by the overlay environment in k8s/overlays/dev/kustomization.yaml
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: pdf-storage
              mountPath: /app/uploads
      volumes:
        - name: pdf-storage
          persistentVolumeClaim:
            claimName: backend-pdf-pvc