apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # namespace: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: multi-app-project-python-app:latest # This will be overridden by the overlay environment in k8s/overlays/dev/kustomization.yaml
          ports:
            - containerPort: 5000
          env:
            - name: API_URL
              value: "" # To be set from overlays/environment
            - name: MYSQL_HOST # Ensure name matching with k8s\base\mysql\configmap.yaml -> MYSQL_HOST as it replaces the value in the container
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST
            - name: MYSQL_DATABASE # Ensure name matching with k8s\base\mysql\configmap.yaml -> MYSQL_DATABASE as it replaces the value in the container
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER # Ensure name matching with k8s\base\mysql\configmap.yaml -> MYSQL_USER as it replaces the value in the container
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD # Ensure name matching with k8s\base\mysql\configmap.yaml -> MYSQL_PASSWORD as it replaces the value in the container
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: pdf-storage
              mountPath: /app/uploads
      volumes:
        - name: pdf-storage
          persistentVolumeClaim:
            claimName: backend-pdf-pvc