# Initializing init-user.sql for MySQL database during runtime as vscode->devcontainer was not picking init-user.sql location.
FROM mysql:8
COPY ./mysql-init/init-user.sql /docker-entrypoint-initdb.d/init-user.sql 
