version: '3.8'
services:
  go-app:
    build: ./go-app
    ports:
      - "8000:8000"

  python-app:
    build: ./python-app
    container_name: python_app
    volumes:
      - ./python-app:/uploads:/app/uploads
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
      - /app/node_modules

  angular-app:
    build: ./angular-app
    ports:
      - "4200:80"

volumes:
  mysql_data: