apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_HOST: mysql
  MYSQL_USER: testuser
  MYSQL_PASSWORD: testpassword
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: userdb
