apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  # namespace: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: multi-app-project-react-app:latest # This will pick the image from the docker desktop (window host)
          ports:
            - containerPort: 3000
