apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  # namespace: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: multi-app-project-mysql-db:latest
          envFrom:
            - configMapRef:
                name: mysql-config
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data  # ← match the volume mount name
          persistentVolumeClaim:
            claimName: mysql-pvc
