namePrefix: dev-
namespace: dev

resources:
  - ../../base

patchesStrategicMerge:
  - patch-pvc-storageclass.yaml

images:
  - name: 816150604527.dkr.ecr.us-east-1.amazonaws.com/react-app
    newTag: dev
  - name: 816150604527.dkr.ecr.us-east-1.amazonaws.com/python-app
    newTag: dev
  - name: 816150604527.dkr.ecr.us-east-1.amazonaws.com/mysql-db
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
